# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HeaderConfigSnapshotTable_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HeaderConfigSnapshotTable(object):
    def setupUi(self, HeaderConfigSnapshotTable):
        HeaderConfigSnapshotTable.setObjectName("HeaderConfigSnapshotTable")
        HeaderConfigSnapshotTable.resize(512, 256)
        self.verticalLayout = QtWidgets.QVBoxLayout(HeaderConfigSnapshotTable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = headerConfView(HeaderConfigSnapshotTable)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(HeaderConfigSnapshotTable)
        QtCore.QMetaObject.connectSlotsByName(HeaderConfigSnapshotTable)

    def retranslateUi(self, HeaderConfigSnapshotTable):
        _translate = QtCore.QCoreApplication.translate
        HeaderConfigSnapshotTable.setWindowTitle(_translate("HeaderConfigSnapshotTable", "Form"))
from hdb_viewer_mem.module.headerConfView import headerConfView
