# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sysconfig_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sysconfig_Form(object):
    def setupUi(self, sysconfig_Form):
        sysconfig_Form.setObjectName("sysconfig_Form")
        sysconfig_Form.resize(319, 167)
        sysconfig_Form.setMaximumSize(QtCore.QSize(16777215, 335))
        self.verticalLayout = QtWidgets.QVBoxLayout(sysconfig_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_pwd = QtWidgets.QLabel(sysconfig_Form)
        self.label_pwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pwd.setObjectName("label_pwd")
        self.gridLayout.addWidget(self.label_pwd, 3, 0, 1, 1)
        self.lineEdit_srv_port = QtWidgets.QLineEdit(sysconfig_Form)
        self.lineEdit_srv_port.setObjectName("lineEdit_srv_port")
        self.gridLayout.addWidget(self.lineEdit_srv_port, 1, 1, 1, 1)
        self.lineEdit_user = QtWidgets.QLineEdit(sysconfig_Form)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout.addWidget(self.lineEdit_user, 2, 1, 1, 1)
        self.lineEdit_svr_addr = QtWidgets.QLineEdit(sysconfig_Form)
        self.lineEdit_svr_addr.setObjectName("lineEdit_svr_addr")
        self.gridLayout.addWidget(self.lineEdit_svr_addr, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_OK = QtWidgets.QPushButton(sysconfig_Form)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.buttonGroup = QtWidgets.QButtonGroup(sysconfig_Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_OK)
        self.horizontalLayout_4.addWidget(self.pushButton_OK)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_Cancel = QtWidgets.QPushButton(sysconfig_Form)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.buttonGroup.addButton(self.pushButton_Cancel)
        self.horizontalLayout_4.addWidget(self.pushButton_Cancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.lineEdit_pwd = QtWidgets.QLineEdit(sysconfig_Form)
        self.lineEdit_pwd.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout.addWidget(self.lineEdit_pwd, 3, 1, 1, 1)
        self.label_svr_addr = QtWidgets.QLabel(sysconfig_Form)
        self.label_svr_addr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_svr_addr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_svr_addr.setObjectName("label_svr_addr")
        self.gridLayout.addWidget(self.label_svr_addr, 0, 0, 1, 1)
        self.label_user = QtWidgets.QLabel(sysconfig_Form)
        self.label_user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_user.setObjectName("label_user")
        self.gridLayout.addWidget(self.label_user, 2, 0, 1, 1)
        self.label_srv_port = QtWidgets.QLabel(sysconfig_Form)
        self.label_srv_port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_srv_port.setObjectName("label_srv_port")
        self.gridLayout.addWidget(self.label_srv_port, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(sysconfig_Form)
        QtCore.QMetaObject.connectSlotsByName(sysconfig_Form)

    def retranslateUi(self, sysconfig_Form):
        _translate = QtCore.QCoreApplication.translate
        sysconfig_Form.setWindowTitle(_translate("sysconfig_Form", "系统配置"))
        self.label_pwd.setText(_translate("sysconfig_Form", "密码:"))
        self.pushButton_OK.setText(_translate("sysconfig_Form", "保存"))
        self.pushButton_Cancel.setText(_translate("sysconfig_Form", "取消"))
        self.label_svr_addr.setText(_translate("sysconfig_Form", "地址:"))
        self.label_user.setText(_translate("sysconfig_Form", "用户名:"))
        self.label_srv_port.setText(_translate("sysconfig_Form", "端口:"))
